### ISSUE TITLE
phenix - real space refine fails in runMolprobityStep

### ISSUE THREAD

**Issue by josuegbl** [scipion-em/scipion-em-phenix#8] opened 2019-10-30 20:00 UTC
We are running using a non-cubic volume that comes from xmipp-extract unit cell and the PDB comes from chimera operate protocol.

THe error is the following:
** Running command: phenix.python /usr/local/scipion/2.0-devel/scipion/software/em/phenix-1.16-3549/modules/phenix/phenix/command_line/real_space_refine.py model_file=/data/dunia/ScipionUserData/projects/TR_TLP_MB/Runs/007359_ChimeraProtOperate/extra/chimeraOut0001.pdb map_file=/data/dunia/ScipionUserData/projects/TR_TLP_MB/Runs/007404_PhenixProtRunRSRefine/extra/real_space.mrc resolution=3.500000 secondary_structure.enabled=False run=minimization_global+adp macro_cycles=5 model_format=pdb+mmcif  
01075:   FINISHED: runRSrefineStep, step 2
01076:     2019-10-30 15:16:39.683603
01077:   STARTED: runMolprobityStep, step 3
01078:     2019-10-30 15:16:39.918174
01079:   
01080:   ============================== Collecting inputs ==============================
01081:   
01082:   Sorry: At least one PDB file is required as input.
01083:   args:  /data/dunia/ScipionUserData/projects/TR_TLP_MB/Runs/007404_PhenixProtRunRSRefine/extra/chimeraOut0001_real_space_refined.cif 
01084:   ** Running command: phenix.python /usr/local/scipion/2.0-devel/scipion/software/em/phenix-1.16-3549/modules/cctbx_project/mmtbx/command_line/molprobity.py /data/dunia/ScipionUserData/projects/TR_TLP_MB/Runs/007404_PhenixProtRunRSRefine/extra/chimeraOut0001_real_space_refined.cif 
01085:   Traceback (most recent call last):
01086:     File "/usr/local/scipion/2.0/scipion/pyworkflow/protocol/protocol.py", line 186, in run
01087:       self._run()
01088:     File "/usr/local/scipion/2.0/scipion/pyworkflow/protocol/protocol.py", line 237, in _run
01089:       resultFiles = self._runFunc()
01090:     File "/usr/local/scipion/2.0/scipion/pyworkflow/protocol/protocol.py", line 233, in _runFunc
01091:       return self._func(*self._args)
01092:     File "/usr/local/scipion/2.0/scipion/software/lib/python2.7/site-packages/phenix/protocols/protocol_real_space_refine.py", line 228, in runMolprobityStep
01093:       cwd=self._getExtraPath())
01094:     File "/usr/local/scipion/2.0/scipion/software/lib/python2.7/site-packages/phenix/__init__.py", line 86, in runPhenixProgram
01095:       pwutils.runJob(None, program, args, env=env, cwd=cwd)
01096:     File "/usr/local/scipion/2.0/scipion/pyworkflow/utils/process.py", line 52, in runJob
01097:       return runCommand(command, env, cwd)
01098:     File "/usr/local/scipion/2.0/scipion/pyworkflow/utils/process.py", line 67, in runCommand
01099:       env=env, cwd=cwd)
01100:     File "/usr/local/scipion/2.0/scipion/software/lib/python2.7/subprocess.py", line 190, in check_call
01101:       raise CalledProcessError(retcode, cmd)
01102:   CalledProcessError: Command 'phenix.python /usr/local/scipion/2.0-devel/scipion/software/em/phenix-1.16-3549/modules/cctbx_project/mmtbx/command_line/molprobity.py /data/dunia/ScipionUserData/projects/TR_TLP_MB/Runs/007404_PhenixProtRunRSRefine/extra/chimeraOut0001_real_space_refined.cif ' returned non-zero exit status 1
01103:   Protocol failed: Command 'phenix.python /usr/local/scipion/2.0-devel/scipion/software/em/phenix-1.16-3549/modules/cctbx_project/mmtbx/command_line/molprobity.py /data/dunia/ScipionUserData/projects/TR_TLP_MB/Runs/007404_PhenixProtRunRSRefine/extra/chimeraOut0001_real_space_refined.cif ' returned non-zero exit status 1
01104:   FAILED: runMolprobityStep, step 3
01105:     2019-10-30 15:16:41.945929
01106:   *** Last status is failed 
01107:   ------------------- PROTOCOL FAILED (DONE 3/5)

**Comment by josuegbl** [comment] 2019-11-28 14:02
Hello @rmarabini and @mmmtnez,
We are trying to run this protocol and always is failing with this type of error. Please, could you have a look to this error? Thanks

**Comment by rmarabini** [comment] 2019-12-19 12:12
Hi @josuegbl,

    The protocol is working here. May I have access to the project? I do not see any other way to further investigate this.

**Comment by rmarabini** [comment] 2020-09-18 10:22
I close this issue since I can not reproduce the problem

**Closed** 2020-09-18 11:50 UTC
